name: Test Student Registration

on:
  push:
  pull_request:

jobs:
  test-html:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v4

      - name: Run HTML tests
        run: |
          chmod +x test.sh
          ./test.sh